### ISSUE TITLE
Fix contact Morse theory

### ISSUE THREAD

**Issue by yhuang85** [yhuang85/mandy#5]
### Tasks

- [x] Fix the $\pi_2^d$-switch section in "Examples", which is completely wrong.
- [x] Move what I thought was a $\pi_2^d$-switch to a new section under "simple $\pi_1$-switches".
- [x] Rename "simple" to "free" and in general polish the "simple $\pi_1$-switches" section.
- [x] Add a section describing the $\pi_2^c$-switches.
